name: Auto Deploy Node App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/ubuntu/book-management-nodejs

    steps:
      - name: Pull latest code
        run: git pull origin master

      - name: Install dependencies
        run: npm install

      - name: Restart app
        run: pm2 restart book-app
